name: Continuous Integration

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: livre
          POSTGRES_USER: jonathan_impe
          POSTGRES_PASSWORD: XgZG4WTHg1WAHMbd
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./projet_chef_d_oeuvre/requirements.txt
        
    - name: Run migrations
      run: python manage.py migrate
      env:
        DJANGO_DB_MODE: dev
        DEBUG: False
        DB_NAME: livre
        DB_USER: jonathan_impe
        DB_PASSWORD: XgZG4WTHg1WAHMbd
        DB_HOST: livre.postgres.database.azure.com
        DB_PORT: 5432
      
    - name: Run tests with coverage
      run: |
        pytest --cov=./ --cov-report=xml
      env:
        DJANGO_DB_MODE: dev
        DEBUG: False
        DB_NAME: livre
        DB_USER: jonathan_impe
        DB_PASSWORD: XgZG4WTHg1WAHMbd
        DB_HOST: livre.postgres.database.azure.com
        DB_PORT: 5432
        
    - name: Check minimum test coverage
      run: |
        coverage report --fail-under=80
      env:
        DJANGO_DB_MODE: dev
        DEBUG: False
        DB_NAME: livre
        DB_USER: jonathan_impe
        DB_PASSWORD: XgZG4WTHg1WAHMbd
        DB_HOST: livre.postgres.database.azure.com
        DB_PORT: 5432
